apiVersion: v1
kind: Service
metadata:
  name: dse-graph-lb
spec:
  selector: 
    app: dse-graph
  type: NodePort
  ports:
  - protocol: TCP 
    port: 9042
    name: cql-port
    nodePort: 32001
  clusterIP: 10.98.123.151
  loadBalancerIP: 10.30.1.17
  type: LoadBalancer   
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155