apiVersion: v1
kind: Service
metadata:
  name: dse-search-lb
spec:
  selector: 
    app: dse-search
  type: NodePort
  ports:
  - protocol: TCP 
    port: 9042
    name: cql-port
  clusterIP: 10.98.123.150
  loadBalancerIP: 10.30.1.16
  type: LoadBalancer   
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155