apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: studio-lb
spec:
  selector:
    matchLabels:
      app: studio-lb
  template:
    metadata:
      labels:
        app: studio-lb
    spec:
      containers:
      - name: studio-lb
        image: datastax/dse-studio:latest
        env:
        - name: DS_LICENSE
          value: accept
        ports:
        - containerPort: 9091
          name: studio-gui-port
        - containerPort: 61620
          name: port-61620
---
apiVersion: v1
kind: Service
metadata:
  name: studio-lb
spec:
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
    nodePort: 
  loadBalancerIP: 
  selector:
    app: studio-lb
  type: LoadBalancer
