---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dse-analytics-1
  labels:
    type: local
    app: dse
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/dse-analytics-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dse-analytics-2
  labels:
    type: local
    app: dse
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/dse-analytics-2
  persistentVolumeReclaimPolicy: Recycle