apiVersion: v1
kind: Service
metadata:
  name: dse-database-lb
spec:
  selector: 
    app: dse-database
  type: NodePort
  ports:
  - protocol: TCP 
    port: 9042
    name: cql-port
    nodePort: 32002 
  clusterIP: 10.98.123.152
  loadBalancerIP: 10.30.1.18
  type: LoadBalancer   
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155